project : segmentation_baseline
experiment_name : resnet34Linknet
savepath : ./segmentation.pt
final_model_path : ./seg_inference.pt
dataset :
  path_to_train_images : 
  path_to_train_masks : 
  path_to_val_images : 
  path_to_val_masks : 
  test_size : 0.2
  img_size_base : [1512,2688]
  img_size_target : [640,1280]
  mean0: 0.485
  mean1: 0.456
  mean2: 0.406
  std0: 0.229
  std1: 0.224
  std2: 0.225

model :
  name : resnet34
  classes : 4
  activation : None

train:
  epochs: 100
  optimizer : Adam
  lr : 0.0003
  momentum : 0.9
  weight_decay : 0.00001
  scheduler : StepLR
  step_size : 40
  gamma : 0.3
  ema : False
  ema_decay : 0.9998
  accumulate_batch_size : 64
  weight_0: 0.5
  weight_1: 0.5

