project : baseline_signal_classification
experiment_name : signal_sslresnet18
savepath : signal.pt
final_model_path: signal_infer.pt

dataset :
  images_path : "/path_to_images"
  labels_path : "/path_to_labels"
  test_size : 0.2
  mean0: 0.485
  mean1: 0.456
  mean2: 0.406
  std0: 0.229
  std1: 0.224
  std2: 0.225
  split_type: stratified

model :
  name : ssl_resnet18
  num_classes : 2
  pretrained : True
  model_type : Single
  num_classes_mt : 2

train:
  epochs: 100
  optimizer : Adam
  lr : 0.0003
  momentum : 0.9
  weight_decay : 0.00001
  scheduler : StepLR
  step_size : 30
  gamma : 0.2
  ema : False
  ema_decay : 0.9998
  accumulate_batch_size : 64
